##### ZJ_Zhang_W4_assn.py

##### There is a question after task4

#### Task1:

Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

- using some numpy functions

In [1]:
import numpy as np

# Task1

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

print("Use intersect1d to output elements common to a and b:", np.intersect1d(a,b))
print("Use setdiff1d to output elements that are not in b in a:", np.setdiff1d(a,b))
print("Use setdiff1d to output elements that are not in a in b:", np.setdiff1d(b,a))
print("Use union1d to output elements common to a and b:", np.union1d(a,b))


Use intersect1d to output elements common to a and b: [2 4]
Use setdiff1d to output elements that are not in b in a: [1 3 5 6]
Use setdiff1d to output elements that are not in a in b: [ 7  8  9 10]
Use union1d to output elements common to a and b: [ 1  2  3  4  5  6  7  8  9 10]


#### Task2:

Create the following 5x3 array
- using reshapt() 
- using T to convert

In [2]:
arr = np.arange(1,16).reshape(3,5)
arr = arr.T
print(arr)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


#### Task3:

a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
removes from array a any items that are also present in array b.
- using delete()

In [3]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

index = [x for x in range(len(a)) for y in range(len(b)) if a[x]==b[y]]

print(np.delete(a,index))

[ 7 15  1  8]


#### Task4:

odometer

##### before doing
- Actually, i have two ideas about this task. And i'm not sure which one is this task asking for.

- First, supposing that i create a whole NumPy array as a odometer one time, which is the plan i made in advance, and it has a 35 days' odometer plan covering the entire distance between NYC and Key West. and i can use the sequence number to show my cumulative miles of every day. 
    This is a simple one, just creating an array.

- Second, i create a NumPy array,which would be populated with the camulative miles of odometer once a day, so i need 35 times to complete this array. And it could be checked using sequence number of date. 
    But the problem is that how can i know that i could complete this ride tour in 35 days? If i can control the ride plan, that means i know the entire plan in advanced. It is contradictory.

- I'm confused with these two ideas. So i tried to solve it in these two ways.

##### the first idea:
- i generate a random array using numpy, and limit the speed and the entire distance.
- you can control the suitable speed by yourself

In [7]:
import numpy as np

# sum is distance from 1 to here
sum = 0
# dist is miles of everyday
dist = 0
# odometer is the miles from 1 day to today.
odometer = np.array

for i in range(32):
    # miles of everyday
    dist = np.random.randint(30, 70)
    sum += dist
    print(sum)
    odometer = np.append(odometer,sum)
    if sum > 1547:
        break

print("\nyou ride",i,"days")
print("\nThe odometer of entire ride:",odometer)

66
98
151
207
259
302
347
406
443
479
518
582
649
697
729
762
825
883
937
996
1031
1075
1108
1154
1221
1275
1328
1368
1414
1448
1498
1551

you ride 31 days

The odometer of entire ride: [<built-in function array> 66 98 151 207 259 302 347 406 443 479 518 582
 649 697 729 762 825 883 937 996 1031 1075 1108 1154 1221 1275 1328 1368
 1414 1448 1498 1551]


##### after : i found that variable sum is no use. sum == odometer

##### the second idea:
- Here i set the day 3 to test, in this task, 31 is needed.

In [5]:
# odometer is the miles from 1 day to today.
odometer = np.array

# in this task, i should from 1 to 31, but here is just a test.
# you can change the number of range.
for i in range(3):
    print("\ninput the day:")
    day = int(input())

    print("\ninput today odometer")
    ot = int(input())
    # generate a array of odometer
    odometer = np.append(odometer,ot)

    if day < 2:
        print("\nThe first day rode",ot,"miles")
    else:
        print("\nToday is the",day,"day")
        print("\nYou have been ridding:",odometer[i+1],"miles")
        
print("see the entire ride odometer:",odometer)


input the day:
1

input today odometer
55

The first day rode 55 miles

input the day:
2

input today odometer
120

Today is the 2 day

You have been ridding: 120 miles

input the day:
3

input today odometer
165

Today is the 3 day

You have been ridding: 165 miles
see the entire ride odometer: [<built-in function array> 55 120 165]


##### after
### Question about numpy:

Here i want to create array by the build-in function: input(), thus i have the variable a belonging to the <build-in function>, 
but the function of numpy array is used by the 'int', 'str', and so on.
When i want to use another function of numpy, it doesn't work.
I have tried many methods to transfer the tyoe, but failed.
I want to know how to solve this problem.
And does the input() can't be used in numpy?

##### Task5:

- What is the maximum yearly NYC consumption of water in millions of gallons per day?
- How many calendar years are represented within this data set? NumPy's shape command is one way to find out.
- What is the mean and the standard deviation of the per capita daily water consumption?
- What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array 
- of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [6]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

# 1. What is the maximum yearly NYC consumption of water in millions of gallons per day?

print("\nmaximum yearly NYC consumption of water is:",np.max(nyc_water[:,2]))


# 2. How many calendar years are represented within this data set? NumPy's shape command is one way to find out.

print("\nnumber of years is:",np.shape(nyc_water)[0]) #return length of the first dimension of the matrix

# 3. What is the mean and the standard deviation of the per capita daily water consumption?

print("\nmean of per capita daily water consumption is:",np.mean(nyc_water[:,3]))
print("\nstandard deviation of per capita daily water consumption is:",np.std(nyc_water[:,3]))


# 4. What is the increase or decrease in population from year to year? Use NumPy's `diff` function 
#   to create an array of differences and save that to a variable called "pop_diff", 
#   then print that variable to the screen.

pop_diff = np.diff(nyc_water[:,1])
print("\nincrease or decrease in population from year to year are:\n",pop_diff)


maximum yearly NYC consumption of water is: 1512.0

number of years is: 39

mean of per capita daily water consumption is: 160.30769230769232

standard deviation of per capita daily water consumption is: 31.51894330370624

increase or decrease in population from year to year are:
 [-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]


C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
